//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputAction/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""4234187d-8ea5-4581-b97a-5c38ac7b61fd"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""4e8ec8c3-d2f2-4911-9bb9-7a6e047d88ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9abb9c8c-433f-44fc-86f3-181f713a8989"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""e46d5299-f1b8-4dca-b08f-2c3f88434777"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""bdca9517-8fec-46cc-a936-71a6d4e4338c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Magnet"",
                    ""type"": ""Button"",
                    ""id"": ""222502af-b87b-4a08-af88-2cf01ca56197"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Size"",
                    ""type"": ""Button"",
                    ""id"": ""283809cf-a6f0-4fbe-8ea5-1b6b25c2d416"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Possess"",
                    ""type"": ""Button"",
                    ""id"": ""5bda219a-0746-4c1c-aace-ea3b4d5e1ad7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeDash"",
                    ""type"": ""Button"",
                    ""id"": ""10393b9a-297a-4379-9799-720237af27d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeMagnet"",
                    ""type"": ""Button"",
                    ""id"": ""cc38f15e-687f-47ef-b38c-1a5f28d0cdcb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeRotation"",
                    ""type"": ""Button"",
                    ""id"": ""3095ba56-6228-4710-ba32-ebf1aea80561"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModePossess"",
                    ""type"": ""Button"",
                    ""id"": ""18749c5e-d934-4b3e-9be6-8ac9910e342a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeSize"",
                    ""type"": ""Button"",
                    ""id"": ""1862a3d2-ba1a-4b81-a286-792fae38c17f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLifeUp"",
                    ""type"": ""Button"",
                    ""id"": ""11cd67c8-3816-497c-9b87-3b0e2a685a61"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl1"",
                    ""type"": ""Button"",
                    ""id"": ""68bd30ff-7ed9-4775-a4ab-1275ba906b94"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl2"",
                    ""type"": ""Button"",
                    ""id"": ""4099917a-2b98-4b61-bf48-4e5282c0d200"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl3"",
                    ""type"": ""Button"",
                    ""id"": ""554a5bff-0154-45c0-b6ee-cda23b478e90"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl4"",
                    ""type"": ""Button"",
                    ""id"": ""44ee7a48-7218-4d7d-b52d-11b1e01aec3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl5"",
                    ""type"": ""Button"",
                    ""id"": ""89007463-f326-4995-b87d-2855050fe203"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeLvl6"",
                    ""type"": ""Button"",
                    ""id"": ""8cb95229-a29c-47cb-b09f-48618dc9680d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GodModeMove"",
                    ""type"": ""Button"",
                    ""id"": ""8a732a27-3db3-4f3b-8828-8d8f763e7f09"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseBoxText"",
                    ""type"": ""Button"",
                    ""id"": ""dac5bd59-dabe-4df5-b19e-0f8887d81be0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""f87a1164-d201-44a8-9390-e28137949fb1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""57636a72-eee8-4c18-b789-b09b2a8ac42c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HubMachine"",
                    ""type"": ""Button"",
                    ""id"": ""bb28986b-68d7-4c58-af1d-1e8fb4d1c2c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0c9a106a-1955-41a8-a065-4956f397270f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""490c9e8f-32b5-41d7-a529-cd9bdeee885e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f63e61b-7559-4809-8bdd-d5befe1b00c7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f694adf6-5b8d-429c-bd6e-39307527c50a"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""737ebc38-c6f0-4ee5-b598-feb1a76b8fe6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3613efc5-1717-40b0-a572-b9d7bf81e5c9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8cce995e-c088-4ef0-bfa5-5a85030cfa20"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""81ce2cf0-3db9-48bb-880a-1178f5d27a8e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""63caa990-3716-4e88-971b-84864ca2bf8d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4eca5a1a-cf71-492e-b1cb-04866f41efde"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""57bbd88d-2c34-4a09-85e5-ca495c63f560"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""652a2a12-d0e2-443a-9b14-e3c52e072458"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9b1f49e1-8459-4567-8a4f-aacde027f835"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""482bc5b2-fe70-484f-b35a-8ab194cba0a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a055dc43-fe8d-45f5-a5ee-a62fb19543e3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e418a3f4-d0eb-4344-81e9-ce095c19a49f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a437f6dd-5469-4043-bccc-2f67ee2d1dc5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd5e8a17-9031-413e-ba25-88586d8f23fa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b6e978d-ac46-4686-b4b9-c7b633cf7027"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b983bd8d-7412-4921-9cbf-c89a071a63a3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""225cb8e1-d835-4405-a149-ac0adf1b5105"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Size"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adb8da86-2992-4031-bc18-d9024b4384d9"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Size"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7badb9cc-317d-4681-8e7d-0f4d1a0cfc24"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Possess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d83643f-82b8-4dee-a03d-6c9067100a86"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Possess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f7a11c1-3ffa-4228-b1c1-2ac3de577ca5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""3150bc11-8112-43fc-88f7-f7c7e7a6f260"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeDash"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""06bf93e3-991c-4594-b33a-a288484ec665"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""349d4ab9-9c2c-4dd4-9e2c-9949394fc477"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""845f0e47-1b59-4661-bd18-eced78212e44"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f4e9ed1e-8744-4f24-b3c9-e6514c20f412"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMagnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""8abd3ded-cca5-48e0-be16-bea83a386143"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMagnet"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""66067a2f-a6cd-4bdc-b06c-ae52e114dddd"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMagnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""7cb9a4b8-e593-4ee1-bca7-20531f813382"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMagnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""47f62bb9-aafe-44f3-888d-abb5dc50205d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMagnet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b32a8969-7326-4cd3-816b-743661894971"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""66573381-d0a7-44f0-b950-bd965aad2560"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""3ba5dce3-67bf-482a-aa31-feb3c1a29edc"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""990578fa-acef-4976-94b3-3e6e71ccb1d1"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6e3b0ba2-6f6e-4d46-807b-cbb7590d3f4a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""076f5497-b0fe-4b26-a975-ce4a522a9709"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModePossess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""477e0b0b-45fd-44d3-a8a7-2ac2cb92f6ed"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModePossess"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""0a2e3c2b-c71b-4c54-905e-d2614c7c2801"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModePossess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""64053b2c-fbdc-4bf4-b4a6-6757eb31d0b3"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModePossess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""739101a2-d9ea-4b59-952f-946318f3dd66"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModePossess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5641209f-ff84-401d-8d41-e9a32e7424e4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeSize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""56b483f8-5c48-4927-a4d2-fab560dc131d"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeSize"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""00d58962-ec50-42d5-8770-0d30530395aa"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeSize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ae0f8512-3988-4e14-a509-ff607eab0c4f"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeSize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5f081b83-f66c-4b98-a768-8b2f8bed3390"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeSize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aa6fc79d-3404-412f-bbec-92475ec96e7f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLifeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""201ee8ff-8483-4a64-81a1-7de35c764766"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLifeUp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""eab82dc9-770b-45df-aedb-b90afb6dddad"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLifeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""98f62d27-0a45-4caf-9262-ef1df9ac0a38"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLifeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""28e269ae-375b-4eb6-a660-e2d53477a465"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLifeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d417031f-3aea-477e-86d5-ebdb0feaf2f5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""bad1969b-0abd-4160-9e7b-892ced1cd3b4"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""43b8bd37-2d2c-4a43-a30d-c4fba049ab11"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""b777fc5f-56d0-45a3-9f48-2a99450fde05"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""72c78891-8201-4061-b2fd-502ce19b3589"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2973036d-b211-4a1f-891d-45f3222287fe"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""5574cfe3-d172-4fa9-8647-25ebfb648d25"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""684a64cb-f327-4a5f-ab5b-067e54e527ce"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""60d961a4-28f6-4d4f-b4ea-fd007e4ce8c7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e1151220-9c08-44ea-a737-617b626e3c61"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bcc12d12-0e87-475a-9ac2-bd8191f6de2a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""55ce30af-b6fd-4728-9372-f1c091dbb9f9"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""186d6f9b-b69e-46cc-8dd8-aac9968f1a13"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""3c1ab2ac-8e31-4197-9f34-248a53096c44"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""599726d6-87b3-4504-8a1a-a217e5751231"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""960ccaad-cded-4e61-8d94-810b5462dd0b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""6dc583b1-6190-47ed-87a8-416f8293b5c8"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""d4148d5f-ce6d-45cd-b807-d961f63f62a6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""bef2a390-7364-48cc-b773-191e413c9575"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fcbe98ba-003f-4e86-a3a6-30cb37b199c4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e4b789d7-a5da-414f-a1d1-8d0ed4866691"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""a5701eb0-50d6-4e07-aea0-1b0498f4bb81"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""2c59a8fa-b7a3-43bf-b4ff-85bb203f6952"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""f4bd56f4-7df4-4115-90ef-d66aae60cb14"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""85ca7f5f-884b-4e45-8faa-b898d4005bc5"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4520020c-d78e-450c-b374-067cdec07114"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""94b150ac-65e3-4696-bc27-5317bb256d16"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl6"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""b9c61405-c5b3-42fb-90aa-9e2ee7150670"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""2fd920df-e0a7-495e-9c8a-b19cba460630"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""f7abbf18-0479-4662-b0ca-4dfaf5fb9d35"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeLvl6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3ca295a5-0146-45e7-b2f8-a77ab19c0d82"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""1c65bb31-e3eb-4f26-b6ba-0d428279f0d5"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""b9c0e4bd-a852-44c2-a183-a7d9b6268e18"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1c20763a-f4b0-4f2c-b216-6f1e59b8873e"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GodModeMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bac43b0a-61bb-481a-a038-44b8ecbd1946"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11fec15a-c77b-44d8-89b5-c9e71499db04"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d89a987-78e7-40c3-b161-36166daca7b7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f52a2c6b-eb0e-4175-8393-7f9e42c3d7d0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b926787-672f-43e4-b24e-90279a76e97e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e8b286e-1760-4f8e-b0b0-78c53b853fe9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32ccffa2-0cd6-411e-844b-c9e319fb09a1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aec695ea-8c78-46d0-b8ca-e156b7b68374"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b5b7ffe-9386-4bd7-979a-34da180ad77d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e78b44ea-a84a-4f6a-8f11-686f5f18449f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7f60d91-420f-4671-9a8e-a3e72671777d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d92d887-5f49-4363-b7ad-dab61b9e4a18"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66513eef-8cd5-4926-a6b4-4ff77d38fb33"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseBoxText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fedd7881-a48d-4294-825c-522888816f67"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28802095-4bc4-4578-afc2-ee861af30096"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f03485c-a1ff-4c69-8ae3-484adefddcd0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eb9c96e-d1ad-4293-ab45-5da88e41a190"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20645306-68f7-470d-8a5c-7c716f275041"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HubMachine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ffe9817-e953-4ac4-bc04-fcd836b81fc0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HubMachine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_Rotation = m_Player.FindAction("Rotation", throwIfNotFound: true);
        m_Player_Magnet = m_Player.FindAction("Magnet", throwIfNotFound: true);
        m_Player_Size = m_Player.FindAction("Size", throwIfNotFound: true);
        m_Player_Possess = m_Player.FindAction("Possess", throwIfNotFound: true);
        m_Player_GodModeDash = m_Player.FindAction("GodModeDash", throwIfNotFound: true);
        m_Player_GodModeMagnet = m_Player.FindAction("GodModeMagnet", throwIfNotFound: true);
        m_Player_GodModeRotation = m_Player.FindAction("GodModeRotation", throwIfNotFound: true);
        m_Player_GodModePossess = m_Player.FindAction("GodModePossess", throwIfNotFound: true);
        m_Player_GodModeSize = m_Player.FindAction("GodModeSize", throwIfNotFound: true);
        m_Player_GodModeLifeUp = m_Player.FindAction("GodModeLifeUp", throwIfNotFound: true);
        m_Player_GodModeLvl1 = m_Player.FindAction("GodModeLvl1", throwIfNotFound: true);
        m_Player_GodModeLvl2 = m_Player.FindAction("GodModeLvl2", throwIfNotFound: true);
        m_Player_GodModeLvl3 = m_Player.FindAction("GodModeLvl3", throwIfNotFound: true);
        m_Player_GodModeLvl4 = m_Player.FindAction("GodModeLvl4", throwIfNotFound: true);
        m_Player_GodModeLvl5 = m_Player.FindAction("GodModeLvl5", throwIfNotFound: true);
        m_Player_GodModeLvl6 = m_Player.FindAction("GodModeLvl6", throwIfNotFound: true);
        m_Player_GodModeMove = m_Player.FindAction("GodModeMove", throwIfNotFound: true);
        m_Player_CloseBoxText = m_Player.FindAction("CloseBoxText", throwIfNotFound: true);
        m_Player_Map = m_Player.FindAction("Map", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_HubMachine = m_Player.FindAction("HubMachine", throwIfNotFound: true);
    }

    ~@PlayerInputAction()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputAction.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_Rotation;
    private readonly InputAction m_Player_Magnet;
    private readonly InputAction m_Player_Size;
    private readonly InputAction m_Player_Possess;
    private readonly InputAction m_Player_GodModeDash;
    private readonly InputAction m_Player_GodModeMagnet;
    private readonly InputAction m_Player_GodModeRotation;
    private readonly InputAction m_Player_GodModePossess;
    private readonly InputAction m_Player_GodModeSize;
    private readonly InputAction m_Player_GodModeLifeUp;
    private readonly InputAction m_Player_GodModeLvl1;
    private readonly InputAction m_Player_GodModeLvl2;
    private readonly InputAction m_Player_GodModeLvl3;
    private readonly InputAction m_Player_GodModeLvl4;
    private readonly InputAction m_Player_GodModeLvl5;
    private readonly InputAction m_Player_GodModeLvl6;
    private readonly InputAction m_Player_GodModeMove;
    private readonly InputAction m_Player_CloseBoxText;
    private readonly InputAction m_Player_Map;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_HubMachine;
    public struct PlayerActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @Rotation => m_Wrapper.m_Player_Rotation;
        public InputAction @Magnet => m_Wrapper.m_Player_Magnet;
        public InputAction @Size => m_Wrapper.m_Player_Size;
        public InputAction @Possess => m_Wrapper.m_Player_Possess;
        public InputAction @GodModeDash => m_Wrapper.m_Player_GodModeDash;
        public InputAction @GodModeMagnet => m_Wrapper.m_Player_GodModeMagnet;
        public InputAction @GodModeRotation => m_Wrapper.m_Player_GodModeRotation;
        public InputAction @GodModePossess => m_Wrapper.m_Player_GodModePossess;
        public InputAction @GodModeSize => m_Wrapper.m_Player_GodModeSize;
        public InputAction @GodModeLifeUp => m_Wrapper.m_Player_GodModeLifeUp;
        public InputAction @GodModeLvl1 => m_Wrapper.m_Player_GodModeLvl1;
        public InputAction @GodModeLvl2 => m_Wrapper.m_Player_GodModeLvl2;
        public InputAction @GodModeLvl3 => m_Wrapper.m_Player_GodModeLvl3;
        public InputAction @GodModeLvl4 => m_Wrapper.m_Player_GodModeLvl4;
        public InputAction @GodModeLvl5 => m_Wrapper.m_Player_GodModeLvl5;
        public InputAction @GodModeLvl6 => m_Wrapper.m_Player_GodModeLvl6;
        public InputAction @GodModeMove => m_Wrapper.m_Player_GodModeMove;
        public InputAction @CloseBoxText => m_Wrapper.m_Player_CloseBoxText;
        public InputAction @Map => m_Wrapper.m_Player_Map;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @HubMachine => m_Wrapper.m_Player_HubMachine;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Magnet.started += instance.OnMagnet;
            @Magnet.performed += instance.OnMagnet;
            @Magnet.canceled += instance.OnMagnet;
            @Size.started += instance.OnSize;
            @Size.performed += instance.OnSize;
            @Size.canceled += instance.OnSize;
            @Possess.started += instance.OnPossess;
            @Possess.performed += instance.OnPossess;
            @Possess.canceled += instance.OnPossess;
            @GodModeDash.started += instance.OnGodModeDash;
            @GodModeDash.performed += instance.OnGodModeDash;
            @GodModeDash.canceled += instance.OnGodModeDash;
            @GodModeMagnet.started += instance.OnGodModeMagnet;
            @GodModeMagnet.performed += instance.OnGodModeMagnet;
            @GodModeMagnet.canceled += instance.OnGodModeMagnet;
            @GodModeRotation.started += instance.OnGodModeRotation;
            @GodModeRotation.performed += instance.OnGodModeRotation;
            @GodModeRotation.canceled += instance.OnGodModeRotation;
            @GodModePossess.started += instance.OnGodModePossess;
            @GodModePossess.performed += instance.OnGodModePossess;
            @GodModePossess.canceled += instance.OnGodModePossess;
            @GodModeSize.started += instance.OnGodModeSize;
            @GodModeSize.performed += instance.OnGodModeSize;
            @GodModeSize.canceled += instance.OnGodModeSize;
            @GodModeLifeUp.started += instance.OnGodModeLifeUp;
            @GodModeLifeUp.performed += instance.OnGodModeLifeUp;
            @GodModeLifeUp.canceled += instance.OnGodModeLifeUp;
            @GodModeLvl1.started += instance.OnGodModeLvl1;
            @GodModeLvl1.performed += instance.OnGodModeLvl1;
            @GodModeLvl1.canceled += instance.OnGodModeLvl1;
            @GodModeLvl2.started += instance.OnGodModeLvl2;
            @GodModeLvl2.performed += instance.OnGodModeLvl2;
            @GodModeLvl2.canceled += instance.OnGodModeLvl2;
            @GodModeLvl3.started += instance.OnGodModeLvl3;
            @GodModeLvl3.performed += instance.OnGodModeLvl3;
            @GodModeLvl3.canceled += instance.OnGodModeLvl3;
            @GodModeLvl4.started += instance.OnGodModeLvl4;
            @GodModeLvl4.performed += instance.OnGodModeLvl4;
            @GodModeLvl4.canceled += instance.OnGodModeLvl4;
            @GodModeLvl5.started += instance.OnGodModeLvl5;
            @GodModeLvl5.performed += instance.OnGodModeLvl5;
            @GodModeLvl5.canceled += instance.OnGodModeLvl5;
            @GodModeLvl6.started += instance.OnGodModeLvl6;
            @GodModeLvl6.performed += instance.OnGodModeLvl6;
            @GodModeLvl6.canceled += instance.OnGodModeLvl6;
            @GodModeMove.started += instance.OnGodModeMove;
            @GodModeMove.performed += instance.OnGodModeMove;
            @GodModeMove.canceled += instance.OnGodModeMove;
            @CloseBoxText.started += instance.OnCloseBoxText;
            @CloseBoxText.performed += instance.OnCloseBoxText;
            @CloseBoxText.canceled += instance.OnCloseBoxText;
            @Map.started += instance.OnMap;
            @Map.performed += instance.OnMap;
            @Map.canceled += instance.OnMap;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @HubMachine.started += instance.OnHubMachine;
            @HubMachine.performed += instance.OnHubMachine;
            @HubMachine.canceled += instance.OnHubMachine;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Magnet.started -= instance.OnMagnet;
            @Magnet.performed -= instance.OnMagnet;
            @Magnet.canceled -= instance.OnMagnet;
            @Size.started -= instance.OnSize;
            @Size.performed -= instance.OnSize;
            @Size.canceled -= instance.OnSize;
            @Possess.started -= instance.OnPossess;
            @Possess.performed -= instance.OnPossess;
            @Possess.canceled -= instance.OnPossess;
            @GodModeDash.started -= instance.OnGodModeDash;
            @GodModeDash.performed -= instance.OnGodModeDash;
            @GodModeDash.canceled -= instance.OnGodModeDash;
            @GodModeMagnet.started -= instance.OnGodModeMagnet;
            @GodModeMagnet.performed -= instance.OnGodModeMagnet;
            @GodModeMagnet.canceled -= instance.OnGodModeMagnet;
            @GodModeRotation.started -= instance.OnGodModeRotation;
            @GodModeRotation.performed -= instance.OnGodModeRotation;
            @GodModeRotation.canceled -= instance.OnGodModeRotation;
            @GodModePossess.started -= instance.OnGodModePossess;
            @GodModePossess.performed -= instance.OnGodModePossess;
            @GodModePossess.canceled -= instance.OnGodModePossess;
            @GodModeSize.started -= instance.OnGodModeSize;
            @GodModeSize.performed -= instance.OnGodModeSize;
            @GodModeSize.canceled -= instance.OnGodModeSize;
            @GodModeLifeUp.started -= instance.OnGodModeLifeUp;
            @GodModeLifeUp.performed -= instance.OnGodModeLifeUp;
            @GodModeLifeUp.canceled -= instance.OnGodModeLifeUp;
            @GodModeLvl1.started -= instance.OnGodModeLvl1;
            @GodModeLvl1.performed -= instance.OnGodModeLvl1;
            @GodModeLvl1.canceled -= instance.OnGodModeLvl1;
            @GodModeLvl2.started -= instance.OnGodModeLvl2;
            @GodModeLvl2.performed -= instance.OnGodModeLvl2;
            @GodModeLvl2.canceled -= instance.OnGodModeLvl2;
            @GodModeLvl3.started -= instance.OnGodModeLvl3;
            @GodModeLvl3.performed -= instance.OnGodModeLvl3;
            @GodModeLvl3.canceled -= instance.OnGodModeLvl3;
            @GodModeLvl4.started -= instance.OnGodModeLvl4;
            @GodModeLvl4.performed -= instance.OnGodModeLvl4;
            @GodModeLvl4.canceled -= instance.OnGodModeLvl4;
            @GodModeLvl5.started -= instance.OnGodModeLvl5;
            @GodModeLvl5.performed -= instance.OnGodModeLvl5;
            @GodModeLvl5.canceled -= instance.OnGodModeLvl5;
            @GodModeLvl6.started -= instance.OnGodModeLvl6;
            @GodModeLvl6.performed -= instance.OnGodModeLvl6;
            @GodModeLvl6.canceled -= instance.OnGodModeLvl6;
            @GodModeMove.started -= instance.OnGodModeMove;
            @GodModeMove.performed -= instance.OnGodModeMove;
            @GodModeMove.canceled -= instance.OnGodModeMove;
            @CloseBoxText.started -= instance.OnCloseBoxText;
            @CloseBoxText.performed -= instance.OnCloseBoxText;
            @CloseBoxText.canceled -= instance.OnCloseBoxText;
            @Map.started -= instance.OnMap;
            @Map.performed -= instance.OnMap;
            @Map.canceled -= instance.OnMap;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @HubMachine.started -= instance.OnHubMachine;
            @HubMachine.performed -= instance.OnHubMachine;
            @HubMachine.canceled -= instance.OnHubMachine;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnMagnet(InputAction.CallbackContext context);
        void OnSize(InputAction.CallbackContext context);
        void OnPossess(InputAction.CallbackContext context);
        void OnGodModeDash(InputAction.CallbackContext context);
        void OnGodModeMagnet(InputAction.CallbackContext context);
        void OnGodModeRotation(InputAction.CallbackContext context);
        void OnGodModePossess(InputAction.CallbackContext context);
        void OnGodModeSize(InputAction.CallbackContext context);
        void OnGodModeLifeUp(InputAction.CallbackContext context);
        void OnGodModeLvl1(InputAction.CallbackContext context);
        void OnGodModeLvl2(InputAction.CallbackContext context);
        void OnGodModeLvl3(InputAction.CallbackContext context);
        void OnGodModeLvl4(InputAction.CallbackContext context);
        void OnGodModeLvl5(InputAction.CallbackContext context);
        void OnGodModeLvl6(InputAction.CallbackContext context);
        void OnGodModeMove(InputAction.CallbackContext context);
        void OnCloseBoxText(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnHubMachine(InputAction.CallbackContext context);
    }
}
